spring:
  application:
    name: badge-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-service:5432/badges
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          dipendente-service:
            url: http://dipendente-service:8070/app/dipendente

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: badge-service
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
          jobStore:
            class: org.quartz.simpl.RAMJobStore
          threadPool:
            threadCount: 3

server:
  port: 8072
