spring:
  application:
    name: dipendente-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-service:5432/dipendenti
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  devtools:
    restart:
      enabled: true  # Abilita il riavvio automatico
      additional-paths: src/main/java  # Assicura che i file Java vengano rilevati
    livereload:
      enabled: true  # Abilita il live reload
  thymeleaf:
    cache: false  # Disabilita il caching di Thymeleaf (se usi template HTML)

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: dipendente-service

jwt:
  secret: "GbOGC6XP6uhqfNUzDIYeqqwO34Ne1EuMOrtsiatc0wo="

server:
  port: 8070
